import static org.testng.Assert.assertTrue;

import org.testng.Assert;
import org.testng.annotations.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class LibraryTest {
   /* @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        Assert.assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
